spring:
  datasource:
    url: jdbc:postgresql://192.168.0.27:5432/primary
    username: postgres
    password: thirumal
   
jdbc:
  primary: ${spring.datasource.url}
  replica: jdbc:postgresql://192.168.0.27:5432/primary

    
logging:
  file:
    name: logs/primary_replica.log 
  level: 
    org.springframework:
      jdbc.datasource.DataSourceTransactionManager: debug