# Primary DB (PostgreSQL)
primary:
  datasource:
    url: jdbc:postgresql://localhost:5432/primary
    jdbcUrl: ${primary.datasource.url}
    username: postgres
    password: thirumal
    driver-class-name: org.postgresql.Driver
    hikari: 
      jdbc-url: ${primary.datasource.url}
      maximum-pool-size: 10
      minimum-idle: 2

# Replica DB 
replica:
  datasource:
    url: jdbc:postgresql://localhost:5432/replica
    jdbcUrl: ${replica.datasource.url}
    username: postgres
    password: thirumal
    driver-class-name: org.postgresql.Driver
    hikari: 
      jdbc-url: ${replica.datasource.url}
      maximum-pool-size: 5
      minimum-idle: 1
    
logging:
  file:
    name: logs/primary_replica.log 
  level: 
    root: INFO
    '[org.springframework]': INFO
    '[jdbc.datasource.DataSourceTransactionManager]': debug